[workspace]
members = ["engine", "game", "resonance", "cadence"]
resolver = "2"

[workspace.package]
version = "1.2.0"
edition = "2024"
license = "MIT"
description = "Journey Engine: A custom 2D game engine built with Rust and wGPU"
repository = "https://github.com/ujjwalvivek/journey"
keywords = ["game-engine", "two-dimensional", "wgpu", "cross-platform"]
