name: Publish Engine to NPM and Github Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Build Wasm Package
        working-directory: ./game
        run: wasm-pack build --target web 

      - name: Rename & Version Package
        working-directory: ./game/pkg
        run: npm pkg set name="@ujjwalvivek/journey-engine" && npm pkg set version="${GITHUB_REF#refs/tags/v}"

      - name: Publish to NPM
        working-directory: ./game/pkg
        run: npm publish --provenance --access public

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Packages
        working-directory: ./game/pkg
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}